# First backend
apiVersion: v1
kind: Service
metadata:
  name: backend1
  labels:
    app: nginx-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: backend1
---
apiVersion: v1
kind: ReplicationController
metadata:
    name: backend1
    labels:
      app: nginx-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: nginx
        image: bprashanth/nginxtest:1.0
        ports:
        - containerPort: 80
---
# Second backend
apiVersion: v1
kind: Service
metadata:
  name: backend2
  labels:
    app: nginx-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: backend2
---
apiVersion: v1
kind: ReplicationController
metadata:
    name: backend2
    labels:
      app: nginx-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: nginx
        image: bprashanth/nginxtest:1.0
        ports:
        - containerPort: 80
---
# Third backend
apiVersion: v1
kind: Service
metadata:
  name: backend3
  labels:
    app: nginx-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: backend3
---
apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-app
    labels:
      app: nginx-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend3
    spec:
      containers:
      - name: nginx
        image: bprashanth/nginxtest:1.0
        ports:
        - containerPort: 80
---
# Https frontend
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: nginx-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      # A secret for each nginx backend container. These secrets need to
      # exist before hand, see README.
      volumes:
      - name: secret
        secret:
          secretName: nginx
      - name: secret1
        secret:
          secretName: nginx1
      - name: secret2
        secret:
          secretName: nginx2
      containers:
      # Frontend nginx has all certs and terminates ssl.
      - name: frontend
        image: bprashanth/nginxrouter:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          # Use Service instead of hostPort.
          hostPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret
        - mountPath: /etc/nginx1/ssl
          name: secret1
        - mountPath: /etc/nginx2/ssl
          name: secret2
